### ISSUE TITLE
Case-insensitive unicode matches?

### ISSUE THREAD

**Issue by glyphobet** [jviereck/regexp.js#1]
Does it support case-insensitive unicode matches? For example, in vanilla JavaScript, you can do this:

```
/ü/i.exec('ü')
["ü"]
/ü/i.exec('Ü')
["Ü"]
```

**Comment by jviereck** [comment]
There are tests for greek letters here:

  https://github.com/jviereck/regexp.js/blob/master/test.js#L178

I've tested your characters on the console and they match :). Therefore, I am going to close this PR.

**Comment by mathiasbynens** [comment]
@jviereck Off-topic, but is there any reason you’re using `String.fromCharCode`? You could just use [escape sequences](http://mathiasbynens.be/notes/javascript-escapes).

E.g. `String.fromCharCode(945)` → `'\u03B1'`.

**Comment by glyphobet** [comment]
Cool. Great presentation, by the way.

**Comment by jviereck** [comment]
> You could just use escape sequences.

Just had not thought about using them - thanks for bringing this up :)

Closing this PR as the feature seems to be implemented.
