### ISSUE TITLE
Lookbehinds?

### ISSUE THREAD

**Issue by alexgorbatchev** [jviereck/regexp.js#2]
First of all, wow - amazing! Thank you so much for this work!

Is there any chance of lookbehind implementation to make this a killer? :)

**Comment by jviereck** [comment]
The goal of the project is to implement the JavaScript RegExp, which does not contain a lookbehind syntax. However, I am happy about adding a switch that enables lookbehind matching as well.

Contribution of this is welcome and might be simple todo. Happy to give an implementation outline. At the moment I don't plan to put time into this as I want to improve the visualization of RegExp first and integrate the debugger on the RegExp's MDN page.

**Comment by alexgorbatchev** [comment]
Thanks for your feedback. It's too bad there isn't a client side alternative to PCRE that could be used on the server (or something similar)
